[package]
name = "containers"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "containers"
path = "src/lib.rs"

[dependencies]
qvek = { git = "https://github.com/platonvin/qvek.git", default-features = false }
